---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  selector:
    app: hello
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30950 # this should be exactly the same what is present in the kind-cluster.yml file value under   extraPortMappings:- containerPort: 30950
      targetPort: http