---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-ref-app
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: springboot-ref-app
          image: yantraqa/spring-ref-app:latest
          ports:
            - containerPort: 9096
        - name:  nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9096