---
apiVersion: v1
kind: Service
metadata:
  name: frontend-1
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30950
  selector:
    app: hello
    tier: frontend


